# Generated by Django 4.2.1 on 2023-05-22 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Absen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('nip', models.CharField(max_length=20)),
                ('tempat_tgl_lahir', models.CharField(max_length=50)),
                ('pangkat_gol_ruang_tmt', models.CharField(max_length=50)),
                ('rekap_bulan', models.CharField(max_length=20)),
                ('tanggal', models.DateField()),
                ('masuk', models.TimeField()),
                ('pulang', models.TimeField()),
                ('jumlah_jam', models.DecimalField(decimal_places=2, max_digits=5)),
                ('jumlah_potongan_tukin', models.DecimalField(decimal_places=2, max_digits=5)),
                ('jabatanstruktural', models.CharField(choices=[('DIREKTUR', 'Direktur'), ('WADIR', 'Wakil Direktur'), ('KETUA_SPMI', 'Ketua SPMI'), ('KABAG_KA_UPT', 'Kabag/Ka. UPT'), ('KAPRODI', 'Kaprodi'), ('SEKPRODI', 'Sekretaris Prodi'), ('KA_LAB', 'Kepala Lab'), ('PENATA_LK', 'Penata LK'), ('BENDAHARA', 'Bendahara'), ('KA_UNIT', 'Kepala Unit'), ('SEKETARIS_DIREKTUR', 'Sekretaris Direktur'), ('OPERATOR_PT', 'Operator PT'), ('KEPALA_ASRAMA', 'Kepala Asrama'), ('DOSEN_STAF', 'Dosen/Staf')], max_length=50)),
                ('unit', models.CharField(choices=[('pengembangan_akademik', 'Pengembangan Akademik'), ('pengembangan_kemahasiswaan', 'Pengembangan Kemahasiswaan'), ('pusat_penelitian_dan_pengabdian_masyarakat', 'Pusat Penelitian Dan Pengabdian Masyarakat'), ('program_studi', 'Program Studi'), ('keuangan', 'Keuangan'), ('kepegawaian', 'Kepegawaian'), ('kerjasama_dan_humas', 'Kerjasama Dan Humas'), ('pusat_inkubasi_bisnis', 'Pusat Inkubasi Bisnis'), ('pusat_perencanaan_dan_pengembangan', 'Pusat Perencanaan Dan Pengembangan'), ('pusat_data_dan_akreditasi', 'Pusat Data Dan Akreditasi'), ('pusat_pengawasan_pengadilan_internal', 'Pusat Pengawasan Pengadilan Internal')], max_length=100)),
                ('program_studi', models.CharField(choices=[('teknik elektronika industri', 'Teknik Elekronika Industri'), ('akutansi', 'Akutansi'), ('teknik informasi', 'Teknologi Informasi'), ('mekatronika', 'Mekatronika')], max_length=30)),
            ],
        ),
    ]
