# Generated by Django 4.2.1 on 2023-05-23 04:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absen',
            name='rekap_bulan',
        ),
    ]
