# Generated by Django 4.2.1 on 2023-07-26 00:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adkep', '0016_remove_pegawaibank_nama_remove_pegawaibank_nip_and_more'),
        ('absen', '0004_absen_alasan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absen',
            name='jabatanstruktural',
        ),
        migrations.AddField(
            model_name='absen',
            name='jabatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adkep.jabatanstruktural'),
        ),
        migrations.AlterField(
            model_name='absen',
            name='unit',
            field=models.CharField(max_length=100),
        ),
    ]
