# Generated by Django 4.2.1 on 2023-07-26 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0005_remove_absen_jabatanstruktural_absen_jabatan_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absen',
            name='unit',
            field=models.CharField(choices=[('pengembangan_akademik', 'Pengembangan Akademik'), ('pengembangan_kemahasiswaan', 'Pengembangan Kemahasiswaan'), ('pusat_penelitian_dan_pengabdian_masyarakat', 'Pusat Penelitian Dan Pengabdian Masyarakat'), ('program_studi', 'Program Studi'), ('keuangan', 'Keuangan'), ('kepegawaian', 'Kepegawaian'), ('kerjasama_dan_humas', 'Kerjasama Dan Humas'), ('pusat_inkubasi_bisnis', 'Pusat Inkubasi Bisnis'), ('pusat_perencanaan_dan_pengembangan', 'Pusat Perencanaan Dan Pengembangan'), ('pusat_data_dan_akreditasi', 'Pusat Data Dan Akreditasi'), ('pusat_pengawasan_pengadilan_internal', 'Pusat Pengawasan Pengadilan Internal')], max_length=100),
        ),
    ]
