# Generated by Django 4.2.1 on 2023-07-26 16:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adkep', '0016_remove_pegawaibank_nama_remove_pegawaibank_nip_and_more'),
        ('absen', '0009_alter_absen_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absen',
            name='jabatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adkep.jabatanstruktural'),
        ),
    ]
