# Generated by Django 4.2.1 on 2023-08-11 18:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adkep', '0018_alter_pegawaipekerjaan_jabatan'),
        ('absen', '0011_alter_absen_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absen',
            name='jabatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adkep.jabatanbawahan'),
        ),
        migrations.AlterField(
            model_name='absen',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
