# Generated by Django 4.2.1 on 2023-08-11 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0012_alter_absen_jabatan_alter_absen_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='absen',
            name='status',
            field=models.CharField(choices=[('BELUM', 'Belum Diverifikasi'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak')], default='BELUM', max_length=20),
        ),
    ]
