# Generated by Django 4.2.1 on 2023-08-12 12:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adkep', '0018_alter_pegawaipekerjaan_jabatan'),
        ('absen', '0013_absen_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absen',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='absen',
            name='nip',
        ),
        migrations.AddField(
            model_name='absen',
            name='pegawaipribadi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adkep.pegawaipribadi'),
        ),
    ]
