# Generated by Django 4.2.1 on 2023-08-13 13:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0014_remove_absen_nama_remove_absen_nip_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absen',
            name='user',
        ),
    ]
