# Generated by Django 4.2.1 on 2023-08-23 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('absen', '0015_remove_absen_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='absen',
            name='pangkat_gol_ruang_tmt',
        ),
        migrations.RemoveField(
            model_name='absen',
            name='program_studi',
        ),
        migrations.RemoveField(
            model_name='absen',
            name='tempat_tgl_lahir',
        ),
        migrations.RemoveField(
            model_name='absen',
            name='unit',
        ),
    ]
