# Generated by Django 4.2.1 on 2023-05-09 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='cutiizin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('nrp', models.IntegerField(null=True)),
                ('jabatan', models.CharField(max_length=40, null=True)),
                ('keperluan', models.CharField(max_length=100)),
                ('tgl_mulai', models.DateField()),
                ('tgl_selesai', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='spt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=40)),
                ('nrp', models.IntegerField(null=True)),
                ('jenis_kegiatan', models.CharField(max_length=100)),
                ('tempat_kegiatan', models.CharField(max_length=10)),
                ('tgl_mulai_kegiatan', models.DateField()),
                ('tgl_selesai_kegiatan', models.DateField()),
            ],
        ),
    ]
