# Generated by Django 4.2.1 on 2023-06-07 04:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perizinan', '0003_alter_cutiizin_jabatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutiizin',
            name='unit',
            field=models.CharField(choices=[('pengembangan_akademik', 'Pengembangan Akademik'), ('pengembangan_kemahasiswaan', 'Pengembangan Kemahasiswaan'), ('pusat_penelitian_dan_pengabdian_masyarakat', 'Pusat Penelitian Dan Pengabdian Masyarakat'), ('program_studi', 'Program Studi'), ('keuangan', 'Keuangan'), ('kepegawaian', 'Kepegawaian'), ('kerjasama_dan_humas', 'Kerjasama Dan Humas'), ('pusat_inkubasi_bisnis', 'Pusat Inkubasi Bisnis'), ('pusat_perencanaan_dan_pengembangan', 'Pusat Perencanaan Dan Pengembangan'), ('pusat_data_dan_akreditasi', 'Pusat Data Dan Akreditasi'), ('pusat_pengawasan_pengadilan_internal', 'Pusat Pengawasan Pengadilan Internal')], max_length=100, null=True),
        ),
    ]
