# Generated by Django 4.2.1 on 2023-06-14 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perizinan', '0004_cutiizin_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='cutiizin',
            name='direksi',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cutiizin',
            name='hari',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cutiizin',
            name='jam',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='cutiizin',
            name='jam_mulai',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='cutiizin',
            name='jam_selesai',
            field=models.TimeField(null=True),
        ),
        migrations.AddField(
            model_name='cutiizin',
            name='ka_unit',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='cutiizin',
            name='verifikasi_direksi',
            field=models.CharField(choices=[('BELUM', 'Belum Diverifikasi'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak')], default='BELUM', max_length=20),
        ),
        migrations.AddField(
            model_name='cutiizin',
            name='verifikasi_kaunit',
            field=models.CharField(choices=[('BELUM', 'Belum Diverifikasi'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak')], default='BELUM', max_length=20),
        ),
        migrations.AddField(
            model_name='cutiizin',
            name='verifikasi_status',
            field=models.CharField(choices=[('BELUM', 'Belum Diverifikasi'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak')], default='BELUM', max_length=20),
        ),
    ]
