# Generated by Django 4.2.1 on 2023-06-22 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perizinan', '0005_cutiizin_direksi_cutiizin_hari_cutiizin_jam_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='atasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jabatan', models.CharField(max_length=50)),
                ('id_atasan', models.CharField(max_length=50)),
                ('id_bawahan', models.CharField(max_length=255)),
            ],
        ),
    ]
