# Generated by Django 4.2.1 on 2023-06-23 02:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perizinan', '0006_atasan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jabatan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterField(
            model_name='cutiizin',
            name='jabatan',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
