# Generated by Django 4.2.1 on 2023-06-25 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('perizinan', '0007_jabatan_alter_cutiizin_jabatan'),
    ]

    operations = [
        migrations.DeleteModel(
            name='atasan',
        ),
    ]
