# Generated by Django 4.2.1 on 2023-08-03 05:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adkep', '0016_remove_pegawaibank_nama_remove_pegawaibank_nip_and_more'),
        ('perizinan', '0012_alter_cutiizin_jabatan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cutiizin',
            name='jabatan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adkep.jabatanstruktural'),
        ),
    ]
