# Generated by Django 4.2.1 on 2023-08-11 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perizinan', '0017_alter_cutiizin_jabatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='spt',
            name='status',
            field=models.CharField(choices=[('BELUM', 'Belum Diverifikasi'), ('DISETUJUI', 'Disetujui'), ('DITOLAK', 'Ditolak')], default='BELUM', max_length=20),
        ),
    ]
