# Generated by Django 4.2.1 on 2023-08-12 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adkep', '0018_alter_pegawaipekerjaan_jabatan'),
        ('perizinan', '0020_alter_spt_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cutiizin',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='cutiizin',
            name='nrp',
        ),
        migrations.RemoveField(
            model_name='spt',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='spt',
            name='nrp',
        ),
        migrations.AddField(
            model_name='cutiizin',
            name='pegawaipribadi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adkep.pegawaipribadi'),
        ),
        migrations.AddField(
            model_name='spt',
            name='pegawaipribadi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adkep.pegawaipribadi'),
        ),
    ]
