# Generated by Django 4.2.1 on 2023-08-23 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perizinan', '0022_remove_cutiizin_user_remove_spt_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='spt',
            name='pegawai_nama',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='spt',
            name='pegawai_nip',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
