# Generated by Django 4.2.1 on 2023-08-25 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adkep', '0018_alter_pegawaipekerjaan_jabatan'),
        ('perizinan', '0024_upload_spt'),
    ]

    operations = [
        migrations.AddField(
            model_name='upload_spt',
            name='pegawaipribadi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adkep.pegawaipribadi'),
        ),
    ]
