# Generated by Django 4.2.1 on 2023-09-04 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('perizinan', '0027_remove_upload_spt_spt_spt_spt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='spt',
            name='pegawai_nama',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='spt',
            name='pegawai_nip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
