# Generated by Django 4.2.1 on 2023-07-06 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Administrator'), ('kaunit', 'Ka.Unit'), ('staf', 'Staf')], max_length=10),
        ),
    ]
