# Generated by Django 4.2.1 on 2023-07-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_user_user_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(blank=True, choices=[('admin', 'Admin'), ('kaunit', 'Ka.Unit'), ('staf', 'Staf')], max_length=10),
        ),
    ]
