# Generated by Django 4.2.1 on 2023-08-03 14:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adkep', '0016_remove_pegawaibank_nama_remove_pegawaibank_nip_and_more'),
        ('login', '0004_alter_user_managers_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jabatan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='adkep.jabatanstruktural'),
        ),
    ]
