# Generated by Django 4.2.1 on 2023-08-08 05:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adkep', '0018_alter_pegawaipekerjaan_jabatan'),
        ('login', '0006_remove_user_jabatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='jabatan',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adkep.jabatanbawahan'),
        ),
    ]
