# Generated by Django 4.2.1 on 2023-06-08 11:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JabatanStruktural',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jabatan', models.CharField(choices=[('ADMIN KEPEGAWAIAN', 'Admin Kepegawaian'), ('DIREKTUR', 'Direktur'), ('WADIR', 'Wakil Direktur I'), ('WADIRII', 'Wakil Direktur II'), ('KETUA_SPMI', 'Ketua SPMI'), ('KABAG_KA_UPT', 'Kabag/Ka. UPT'), ('KAPRODI_ELEKTRO', 'Kaprodi Elektronika'), ('KAPRODI_TEKNOLOGI_INFORMASI', 'Kaprodi Teknologi Informasi'), ('KAPRODI_MEKATRONIKA', 'Kaprodi Mekatronika'), ('KAPRODIAKUTANSI', 'Kaprodi Akutansi'), ('KAPRODI_AKUTANSI_SEKTORPUBLIK', 'Kaprodi Akutansi Sektor Publik'), ('ADMINPUSTAKA', 'Admin Pustaka'), ('ADMIN AKADEMIK', 'Admin Akademik'), ('ADMIN PEMBELAJARAN', 'Admin Pembelajaran'), ('ADMIN KEMAHASISWAAN', 'Admin Kemahasiswaan'), ('SEKPRODI', 'Sekretaris Prodi Teknologi Informasi'), ('SEKPRODI', 'Sekretaris Prodi Elektronika'), ('SEKPRODI', 'Sekretaris Prodi Mekatronika'), ('SEKPRODI', 'Sekretaris Prodi Akutansi'), ('SEKPRODI', 'Sekretaris Prodi Akutansi Sektor Publik'), ('KA_LAB', 'Ka Lab Teknologi Informasi'), ('KA_LAB', 'Ka Lab Elektonika'), ('KA_LAB', 'Ka Lab Mekatronika'), ('KA_LAB', 'Ka Lab Akutansi'), ('KA_LAB', 'Ka Lab Akutansi Sektor Publik'), ('PENATA_LK', 'Penata LK'), ('BENDAHARA', 'Bendahara'), ('KA_UNIT', 'Kepala Unit'), ('SEKETARIS_DIREKTUR', 'Sekretaris Direktur'), ('OPERATOR_PT', 'Operator PT'), ('KEPALA_ASRAMA', 'Kepala Asrama'), ('DOSEN', 'Dosen Teknologi Informasi'), ('DOSEN', 'Dosen Elektronika'), ('DOSEN', 'Dosen Mekatronika'), ('DOSEN', 'Dosen Akutansi'), ('DOSEN', 'Dosen Akutansi Sektor Publik'), ('STAF', 'Staf'), ('TEKNISI', 'Teknisi')], max_length=50)),
                ('status_jabatan', models.CharField(choices=[('TETAP', 'Tetap'), ('HONOR', 'Honor')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='PegawaiBank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_rek_bank', models.CharField(blank=True, max_length=20, null=True)),
                ('nama_bank', models.CharField(blank=True, max_length=50, null=True)),
                ('cabang', models.CharField(blank=True, max_length=50, null=True)),
                ('atasnama', models.CharField(blank=True, max_length=50, null=True)),
                ('npwp', models.CharField(blank=True, max_length=20, null=True)),
                ('no_bpjs_tenagakerja', models.CharField(blank=True, max_length=20, null=True)),
                ('no_bpjs_kesehatan', models.CharField(blank=True, max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PegawaiKeluarga',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_pasangan', models.CharField(blank=True, max_length=40, null=True)),
                ('tempat_lahir', models.CharField(blank=True, max_length=50, null=True)),
                ('tgl_lahir', models.DateField(blank=True, null=True)),
                ('hp', models.CharField(blank=True, max_length=20, null=True)),
                ('anak1', models.CharField(blank=True, max_length=40, null=True)),
                ('jk4', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, null=True)),
                ('tgl_lahir_a1', models.DateField(blank=True, null=True)),
                ('anak2', models.CharField(blank=True, max_length=40, null=True)),
                ('tgl_lahir_a2', models.DateField(blank=True, null=True)),
                ('jk6', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, null=True)),
                ('anak3', models.CharField(blank=True, max_length=40, null=True)),
                ('jk8', models.CharField(blank=True, choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1, null=True)),
                ('tgl_lahir_a3', models.DateField(blank=True, null=True)),
                ('jumlah_anak', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PegawaiPendidikan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pendidikan_terakhir', models.CharField(max_length=50)),
                ('perguruan_d3', models.CharField(blank=True, max_length=100, null=True)),
                ('bidang_d3', models.CharField(blank=True, max_length=100, null=True)),
                ('perguruan_tinggi_d4_s1', models.CharField(blank=True, max_length=100, null=True)),
                ('bidang_d4_s1', models.CharField(blank=True, max_length=100, null=True)),
                ('perguruan_tinggi_sp1_s2', models.CharField(blank=True, max_length=100, null=True)),
                ('bidang_sp1_s2', models.CharField(blank=True, max_length=100, null=True)),
                ('perguruan_tinggi_sp2_s3', models.CharField(blank=True, max_length=100, null=True)),
                ('bidang_sp2_s3', models.CharField(blank=True, max_length=100, null=True)),
                ('sertifikat_keahlian', models.ImageField(blank=True, null=True, upload_to='pegawaipendidikan/')),
                ('masa_berlaku', models.DateField(blank=True, null=True)),
                ('organisasi_profesi', models.CharField(blank=True, max_length=100, null=True)),
                ('kurun_waktu', models.CharField(blank=True, max_length=100, null=True)),
                ('tingkat', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PegawaiPribadi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='pegawai/')),
                ('nama', models.CharField(max_length=40)),
                ('nrp_kontrak', models.CharField(max_length=20)),
                ('nrp_tetap', models.CharField(max_length=20)),
                ('nip', models.CharField(max_length=20)),
                ('gelar', models.CharField(max_length=20)),
                ('jenis_kelamin', models.CharField(choices=[('L', 'Laki-laki'), ('P', 'Perempuan')], max_length=1)),
                ('tgl_lahir', models.DateField()),
                ('gol_darah', models.CharField(choices=[('A', 'A'), ('B', 'B'), ('AB', 'AB'), ('O', 'O')], max_length=2)),
                ('agama', models.CharField(max_length=20)),
                ('jalan', models.CharField(max_length=50)),
                ('nmr_rumah', models.CharField(max_length=10)),
                ('desa', models.CharField(max_length=50)),
                ('kecamatan', models.CharField(max_length=50)),
                ('kabupaten', models.CharField(max_length=50)),
                ('provinsi', models.CharField(max_length=50)),
                ('kode_pos', models.CharField(max_length=10)),
                ('tlp_rumah', models.CharField(max_length=20)),
                ('hp', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Provinsi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_provinsi', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='PegawaiPekerjaan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mulai_kerja', models.DateField()),
                ('lama_kerja', models.IntegerField()),
                ('pegawai', models.CharField(choices=[('tetap', 'Pegawai Tetap'), ('honor', 'Pegawai Honor'), ('pns', 'Pegawai PNS')], max_length=10)),
                ('status', models.CharField(choices=[('aktif', 'Aktif'), ('keluar', 'Keluar'), ('resign', 'Resign'), ('tidak_aktif', 'Tidak Aktif'), ('tugas_belajar', 'Tugas Belajar'), ('izin_belajar', 'Izin Belajar')], max_length=15)),
                ('posisi', models.CharField(choices=[('dosen', 'Dosen'), ('staf', 'Staf'), ('administrasi', 'Administrasi'), ('pustakawan', 'Pustakawan'), ('teknisi', 'Teknisi'), ('rumah_tangga', 'Rumah Tangga')], max_length=15)),
                ('unit', models.CharField(choices=[('pengembangan_akademik', 'Pengembangan Akademik'), ('pengembangan_kemahasiswaan', 'Pengembangan Kemahasiswaan'), ('pusat_penelitian_dan_pengabdian_masyarakat', 'Pusat Penelitian Dan Pengabdian Masyarakat'), ('program_studi', 'Program Studi'), ('keuangan', 'Keuangan'), ('kepegawaian', 'Kepegawaian'), ('kerjasama_dan_humas', 'Kerjasama Dan Humas'), ('pusat_inkubasi_bisnis', 'Pusat Inkubasi Bisnis'), ('pusat_perencanaan_dan_pengembangan', 'Pusat Perencanaan Dan Pengembangan'), ('pusat_data_dan_akreditasi', 'Pusat Data Dan Akreditasi'), ('pusat_pengawasan_pengadilan_internal', 'Pusat Pengawasan Pengadilan Internal')], max_length=100)),
                ('program_studi', models.CharField(choices=[('teknik elektronika industri', 'Teknik Elekronika Industri'), ('akutansi', 'Akutansi'), ('teknik informasi', 'Teknologi Informasi'), ('mekatronika', 'Mekatronika'), ('STAF', 'Staf')], max_length=30)),
                ('berhenti_kerja', models.DateField(blank=True, null=True)),
                ('alasan', models.CharField(blank=True, max_length=100, null=True)),
                ('tmt', models.DateField(blank=True, null=True)),
                ('tst', models.DateField(blank=True, null=True)),
                ('NIDN_NUP_NITL_NIDK', models.CharField(blank=True, max_length=20, null=True)),
                ('jabatan_fungsional', models.CharField(blank=True, max_length=50, null=True)),
                ('gol', models.CharField(blank=True, max_length=10, null=True)),
                ('sertifikasi_dosen', models.ImageField(blank=True, null=True, upload_to='pegawaipekerjaan/')),
                ('no_sertifikasi_dosen', models.CharField(blank=True, max_length=20, null=True)),
                ('jabatanstruktural', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='adkep.jabatanstruktural')),
            ],
        ),
        migrations.CreateModel(
            name='Kabupaten',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_kabupaten', models.CharField(max_length=255)),
                ('provinsi_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adkep.provinsi')),
            ],
        ),
    ]
