# Generated by Django 4.2.1 on 2023-06-09 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adkep', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jabatanstruktural',
            name='nama_jabatan',
            field=models.CharField(choices=[('Admin Kepegawaian', 'ADMIN KEPEGAWAIAN'), ('Direktur', 'DIREKTUR'), ('Wakil Direktur I', 'WADIR'), ('Wakil Direktur II', 'WADIRII'), ('Ketua SPMI', 'KETUA_SPMI'), ('Kabag/Ka. UPT', 'KABAG_KA_UPT'), ('Kaprodi Elektronika', 'KAPRODI_ELEKTRO'), ('Kaprodi Teknologi Informasi', 'KAPRODI_TEKNOLOGI_INFORMASI'), ('Kaprodi Mekatronika', 'KAPRODI_MEKATRONIKA'), ('Kaprodi Akutansi', 'KAPRODIAKUTANSI'), ('Kaprodi Akutansi Sektor Publik', 'KAPRODI_AKUTANSI_SEKTORPUBLIK'), ('Admin Pustaka', 'ADMINPUSTAKA'), ('Admin Akademik', 'ADMIN AKADEMIK'), ('Admin Pembelajaran', 'ADMIN PEMBELAJARAN'), ('Admin Kemahasiswaan', 'ADMIN KEMAHASISWAAN'), ('Sekretaris Prodi Teknologi Informasi', 'SEKPRODI'), ('Sekretaris Prodi Elektronika', 'SEKPRODI'), ('Sekretaris Prodi Mekatronika', 'SEKPRODI'), ('Sekretaris Prodi Akutansi', 'SEKPRODI'), ('Sekretaris Prodi Akutansi Sektor Publik', 'SEKPRODI'), ('Ka Lab Teknologi Informasi', 'KA_LAB'), ('Ka Lab Elektronika', 'KA_LAB'), ('Ka Lab Mekatronika', 'KA_LAB'), ('Ka Lab Akutansi', 'KA_LAB'), ('Ka Lab Akutansi Sektor Publik', 'KA_LAB'), ('Penata LK', 'PENATA_LK'), ('Bendahara', 'BENDAHARA'), ('Kepala Unit', 'KA_UNIT'), ('Sekretaris Direktur', 'SEKETARIS_DIREKTUR'), ('Operator PT', 'OPERATOR_PT'), ('Kepala Asrama', 'KEPALA_ASRAMA'), ('Dosen Teknologi Informasi', 'DOSEN'), ('Dosen Elektronika', 'DOSEN'), ('Dosen Mekatronika', 'DOSEN'), ('Dosen Akutansi', 'DOSEN'), ('Dosen Akutansi Sektor Publik', 'DOSEN'), ('Staf', 'STAF'), ('Teknisi', 'TEKNISI')], max_length=50),
        ),
    ]
