# Generated by Django 4.2.1 on 2023-07-12 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adkep', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jabatanstruktural',
            name='status_jabatan',
        ),
        migrations.AddField(
            model_name='jabatanstruktural',
            name='id_atasan',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='jabatanstruktural',
            name='id_bawahan',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='jabatanstruktural',
            name='nama_jabatan',
            field=models.CharField(max_length=100),
        ),
    ]
