# Generated by Django 4.2.1 on 2023-06-12 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adkep', '0002_alter_jabatanstruktural_nama_jabatan'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawaibank',
            name='nama',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pegawaibank',
            name='nip',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pegawaikeluarga',
            name='nama',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pegawaikeluarga',
            name='nip',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pegawaipekerjaan',
            name='nama',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pegawaipekerjaan',
            name='nip',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='pegawaipendidikan',
            name='nama',
            field=models.CharField(max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='pegawaipendidikan',
            name='nip',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
