# Generated by Django 4.2.1 on 2023-07-18 04:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adkep', '0002_remove_jabatanstruktural_status_jabatan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawaipribadi',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
