# Generated by Django 4.2.1 on 2023-05-06 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adkep', '0002_pegawai_nrp'),
    ]

    operations = [
        migrations.CreateModel(
            name='Absen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=10)),
                ('keterangan', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='pegawai',
            name='absen_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adkep.absen'),
        ),
    ]
