# Generated by Django 4.2.1 on 2023-05-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adkep', '0003_absen_pegawai_absen_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='absen',
            name='masuk',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='absen',
            name='pulang',
            field=models.IntegerField(null=True),
        ),
    ]
