# Generated by Django 4.2.1 on 2023-05-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adkep', '0005_rename_absen_id_pegawai_status_pegawai_hp'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawai',
            name='jabatan',
            field=models.CharField(max_length=40, null=True),
        ),
    ]
