# Generated by Django 4.2.1 on 2023-05-08 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adkep', '0008_alter_absen_masuk_alter_absen_pulang'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absen',
            name='masuk',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='absen',
            name='pulang',
            field=models.IntegerField(null=True),
        ),
    ]
