# Generated by Django 4.2.1 on 2023-07-19 04:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adkep', '0008_alter_pegawaipribadi_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pegawaipribadi',
            name='id',
        ),
        migrations.AlterField(
            model_name='pegawaipribadi',
            name='user',
            field=models.OneToOneField(default=10, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
