# Generated by Django 4.2.1 on 2023-07-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adkep', '0010_alter_pegawaipribadi_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pegawaipendidikan',
            old_name='bidang_d3',
            new_name='bidang',
        ),
        migrations.RenameField(
            model_name='pegawaipendidikan',
            old_name='perguruan_d3',
            new_name='perguruan',
        ),
        migrations.RemoveField(
            model_name='pegawaipendidikan',
            name='bidang_d4_s1',
        ),
        migrations.RemoveField(
            model_name='pegawaipendidikan',
            name='bidang_sp1_s2',
        ),
        migrations.RemoveField(
            model_name='pegawaipendidikan',
            name='bidang_sp2_s3',
        ),
        migrations.RemoveField(
            model_name='pegawaipendidikan',
            name='perguruan_tinggi_d4_s1',
        ),
        migrations.RemoveField(
            model_name='pegawaipendidikan',
            name='perguruan_tinggi_sp1_s2',
        ),
        migrations.RemoveField(
            model_name='pegawaipendidikan',
            name='perguruan_tinggi_sp2_s3',
        ),
        migrations.RemoveField(
            model_name='pegawaipribadi',
            name='email',
        ),
    ]
