# Generated by Django 4.2.1 on 2023-05-09 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adkep', '0010_absen_nama_absen_nrp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='absen',
            name='masuk',
            field=models.TimeField(null=True),
        ),
        migrations.AlterField(
            model_name='absen',
            name='pulang',
            field=models.TimeField(null=True),
        ),
    ]
