# Generated by Django 4.2.1 on 2023-07-20 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adkep', '0011_rename_bidang_d3_pegawaipendidikan_bidang_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pegawaipribadi',
            name='pekerjaan',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='adkep.pegawaipekerjaan'),
        ),
    ]
