# Generated by Django 4.2.1 on 2023-07-24 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adkep', '0015_pegawaipribadi_bank_pegawaipribadi_keluarga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pegawaibank',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='pegawaibank',
            name='nip',
        ),
        migrations.RemoveField(
            model_name='pegawaikeluarga',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='pegawaikeluarga',
            name='nip',
        ),
        migrations.RemoveField(
            model_name='pegawaipekerjaan',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='pegawaipekerjaan',
            name='nip',
        ),
        migrations.RemoveField(
            model_name='pegawaipendidikan',
            name='nama',
        ),
        migrations.RemoveField(
            model_name='pegawaipendidikan',
            name='nip',
        ),
    ]
