# Generated by Django 4.2.1 on 2023-08-06 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adkep', '0016_remove_pegawaibank_nama_remove_pegawaibank_nip_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='JabtanAtasan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jabatan', models.CharField(max_length=100)),
            ],
        ),
        migrations.RemoveField(
            model_name='pegawaipribadi',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='pegawaipribadi',
            name='keluarga',
        ),
        migrations.RemoveField(
            model_name='pegawaipribadi',
            name='pekerjaan',
        ),
        migrations.RemoveField(
            model_name='pegawaipribadi',
            name='pendidikan',
        ),
        migrations.AddField(
            model_name='pegawaibank',
            name='pegawaipribadi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adkep.pegawaipribadi'),
        ),
        migrations.AddField(
            model_name='pegawaikeluarga',
            name='pegawaipribadi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adkep.pegawaipribadi'),
        ),
        migrations.AddField(
            model_name='pegawaipekerjaan',
            name='pegawaipribadi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adkep.pegawaipribadi'),
        ),
        migrations.AddField(
            model_name='pegawaipendidikan',
            name='pegawaipribadi',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adkep.pegawaipribadi'),
        ),
        migrations.CreateModel(
            name='JabatanBawahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nama_jabatan', models.CharField(max_length=100)),
                ('atasan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adkep.jabtanatasan')),
            ],
        ),
    ]
