# Generated by Django 4.2.1 on 2023-08-07 06:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adkep', '0017_jabtanatasan_remove_pegawaipribadi_bank_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawaipekerjaan',
            name='jabatan',
            field=models.ForeignKey(max_length=100, null=True, on_delete=django.db.models.deletion.CASCADE, to='adkep.jabatanbawahan'),
        ),
    ]
