# Generated by Django 4.2.1 on 2023-08-28 22:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adkep', '0019_alter_pegawaikeluarga_anak1_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='KoneksiAtasanBawahan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atasan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adkep.jabtanatasan')),
                ('bawahan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adkep.jabatanbawahan')),
            ],
        ),
    ]
