# Generated by Django 4.2.1 on 2023-08-31 02:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adkep', '0020_koneksiatasanbawahan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pegawaipekerjaan',
            name='program_studi',
            field=models.CharField(choices=[('teknik elektronika industri', 'Teknik Elekronika Industri'), ('akutansi', 'Akutansi'), ('teknik informasi', 'Teknologi Informasi'), ('mekatronika', 'Mekatronika'), ('STAF', '-')], max_length=30),
        ),
        migrations.AlterField(
            model_name='pegawaipekerjaan',
            name='unit',
            field=models.CharField(choices=[('pengembangan_akademik', 'Pengembangan Akademik'), ('pengembangan_kemahasiswaan', 'Pengembangan Kemahasiswaan'), ('pusat_penelitian_dan_pengabdian_masyarakat', 'Pusat Penelitian Dan Pengabdian Masyarakat'), ('program_studi', 'Program Studi'), ('keuangan', 'Keuangan'), ('kepegawaian', 'Kepegawaian'), ('kerjasama_dan_humas', 'Kerjasama Dan Humas'), ('pusat_inkubasi_bisnis', 'Pusat Inkubasi Bisnis'), ('pusat_perencanaan_dan_pengembangan', 'Pusat Perencanaan Dan Pengembangan'), ('pusat_data_dan_akreditasi', 'Pusat Data Dan Akreditasi'), ('pusat_pengawasan_pengadilan_internal', 'Pusat Pengawasan Pengadilan Internal'), ('kosong', '-')], max_length=100),
        ),
    ]
