# Generated by Django 4.2.1 on 2023-08-14 05:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adkep', '0018_alter_pegawaipekerjaan_jabatan'),
    ]

    operations = [
        migrations.CreateModel(
            name='Nilai',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kerapian', models.CharField(max_length=100)),
                ('kesopanan', models.CharField(max_length=100)),
                ('dedikasi', models.CharField(max_length=100)),
                ('loyalitas', models.CharField(max_length=100)),
                ('disiplin', models.CharField(max_length=100)),
                ('kerjasama', models.CharField(max_length=100)),
                ('tupoksi', models.CharField(max_length=100)),
                ('rata_rata', models.CharField(max_length=100)),
                ('nilai_huruf', models.CharField(max_length=100)),
                ('potongan', models.CharField(max_length=100)),
                ('pegawaipribadi', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='adkep.pegawaipribadi')),
            ],
        ),
    ]
